In [39]:
import numpy as np
#from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
#df=load_iris()
df=pd.read_csv('iris_dataset.csv')
d={'virginica': 0, 'setosa': 1, 'versicolor': 2}

In [43]:
print(type(df))
#x=df.data
#y=df.target
#print(x+y)
#print(y)

<class 'pandas.core.frame.DataFrame'>


In [44]:
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

In [48]:
def change_encoding(row):
    row['species']=d[row['species']]
    return row
df=df.apply(change_encoding,axis=1)
df.to_csv('iris2.csv', sep=',', encoding='utf-8')
#df[''] = df['A'].apply(lambda x: x+1)

KeyError: (1.0, 'occurred at index 0')

In [20]:
#x=df.data
#y=df.target
#print(x)
#print(y)

In [37]:
#Reading data from csv file
cols = np.loadtxt("iris_dataset.csv",delimiter=',',usecols=(0,1,2,3,4),unpack=True) #Read in comma separated data
#Usecols() will give how many columns to read
#Form the usual "X" matrix and "y" vector
X = np.transpose(np.array(cols[:-1]))
#print(X)
y = np.transpose(np.array(cols[-1:]))
#print(y)
m = y.size # number of training examples
#Insert the usual column of 1's into the "X" matrix
X = np.insert(X,0,1,axis=1)
#numpy.insert(arr, obj, values, axis) will broadcast 1 to all rows and will make a column

ValueError: could not convert string to float: 'Iris-setosa'

In [11]:
print(X)

[[1.  5.1 3.5 1.4]
 [1.  4.9 3.  1.4]
 [1.  4.7 3.2 1.3]
 [1.  4.6 3.1 1.5]
 [1.  5.  3.6 1.4]
 [1.  5.4 3.9 1.7]
 [1.  4.6 3.4 1.4]
 [1.  5.  3.4 1.5]
 [1.  4.4 2.9 1.4]
 [1.  4.9 3.1 1.5]
 [1.  5.4 3.7 1.5]
 [1.  4.8 3.4 1.6]
 [1.  4.8 3.  1.4]
 [1.  4.3 3.  1.1]
 [1.  5.8 4.  1.2]
 [1.  5.7 4.4 1.5]
 [1.  5.4 3.9 1.3]
 [1.  5.1 3.5 1.4]
 [1.  5.7 3.8 1.7]
 [1.  5.1 3.8 1.5]
 [1.  5.4 3.4 1.7]
 [1.  5.1 3.7 1.5]
 [1.  4.6 3.6 1. ]
 [1.  5.1 3.3 1.7]
 [1.  4.8 3.4 1.9]
 [1.  5.  3.  1.6]
 [1.  5.  3.4 1.6]
 [1.  5.2 3.5 1.5]
 [1.  5.2 3.4 1.4]
 [1.  4.7 3.2 1.6]
 [1.  4.8 3.1 1.6]
 [1.  5.4 3.4 1.5]
 [1.  5.2 4.1 1.5]
 [1.  5.5 4.2 1.4]
 [1.  4.9 3.1 1.5]
 [1.  5.  3.2 1.2]
 [1.  5.5 3.5 1.3]
 [1.  4.9 3.1 1.5]
 [1.  4.4 3.  1.3]
 [1.  5.1 3.4 1.5]
 [1.  5.  3.5 1.3]
 [1.  4.5 2.3 1.3]
 [1.  4.4 3.2 1.3]
 [1.  5.  3.5 1.6]
 [1.  5.1 3.8 1.9]
 [1.  4.8 3.  1.4]
 [1.  5.1 3.8 1.6]
 [1.  4.6 3.2 1.4]
 [1.  5.3 3.7 1.5]
 [1.  5.  3.3 1.4]
 [1.  7.  3.2 4.7]
 [1.  6.4 3.2 4.5]
 [1.  6.9 3.

In [36]:
print(y)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.1]
 [0.2]
 [0.4]
 [0.4]
 [0.3]
 [0.3]
 [0.3]
 [0.2]
 [0.4]
 [0.2]
 [0.5]
 [0.2]
 [0.2]
 [0.4]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.1]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.3]
 [0.3]
 [0.2]
 [0.6]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [1.4]
 [1.5]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.6]
 [1. ]
 [1.3]
 [1.4]
 [1. ]
 [1.5]
 [1. ]
 [1.4]
 [1.3]
 [1.4]
 [1.5]
 [1. ]
 [1.5]
 [1.1]
 [1.8]
 [1.3]
 [1.5]
 [1.2]
 [1.3]
 [1.4]
 [1.4]
 [1.7]
 [1.5]
 [1. ]
 [1.1]
 [1. ]
 [1.2]
 [1.6]
 [1.5]
 [1.6]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.2]
 [1.4]
 [1.2]
 [1. ]
 [1.3]
 [1.2]
 [1.3]
 [1.3]
 [1.1]
 [1.3]
 [2.5]
 [1.9]
 [2.1]
 [1.8]
 [2.2]
 [2.1]
 [1.7]
 [1.8]
 [1.8]
 [2.5]
 [2. ]
 [1.9]
 [2.1]
 [2. ]
 [2.4]
 [2.3]
 [1.8]
 [2.2]
 [2.3]
 [1.5]
 [2.3]
 [2. ]
 [2. ]
 [1.8]
 [2.1]
 [1.8]
 [1.8]
 [1.8]
 [2.1]
 [1.6]
 [1.9]
 [2. ]
 [2.2]
 [1.5]
 [1.4]
 [2.3]
 [2.4]
 [1.8]
 [1.8]
 [2.1]
 [2.4]
 [2.3]
 [1.9]